### ISSUE TITLE
Addressbook.java Code Coverage

### ISSUE THREAD

**Issue by reiterj1** [erikkgagewhitt/chatty#40]
### Description
Code coverage for the Addressbook.java file can be increased.

### Acceptance Criteria

- [x] tests added for commandGet method
- [x] tests added for commandAdd method

**Comment by erikkgagewhitt** [comment]
@reiterj1 Hey, great job on writing up the issue! Thanks for getting this all set up. On left hand panel there are some areas to fill in with Zenhub now that you have it. I went ahead and changed the Milestone to the new sprint since I forgot to add it (woops). I also added you as the assignee and changed the pipeline to "in progress." The only thing left to do is add an estimate which you won't know until you finish, so again, great job and thanks!
